#!/bin/bash
set -euo pipefail

# ── Configuration ──
APP_NAME="Glimpse"
BUNDLE_ID="com.yifuwu.glimpse"
VERSION="0.2.3"
BUILD_NUMBER="1"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BUILD_DIR="$SCRIPT_DIR/.build"
APP_DIR="$BUILD_DIR/$APP_NAME.app"
DMG_NAME="$APP_NAME-$VERSION"

# Signing identity: set CODESIGN_IDENTITY env var, or "ad-hoc" for testing
SIGN_ID="${CODESIGN_IDENTITY:--}"

echo "=== Building $APP_NAME v$VERSION (build $BUILD_NUMBER) ==="

# ── Step 0: Embed API keys (if provided via env vars) ──
KEYS_FILE="$SCRIPT_DIR/Glimpse/EmbeddedKeys.swift"
EMBED_ANTHROPIC="${GLIMPSE_ANTHROPIC_KEY:-}"
EMBED_OPENAI="${GLIMPSE_OPENAI_KEY:-}"
EMBED_GEMINI="${GLIMPSE_GEMINI_KEY:-}"

if [ -n "$EMBED_ANTHROPIC" ] || [ -n "$EMBED_OPENAI" ] || [ -n "$EMBED_GEMINI" ]; then
    echo "[0/6] Embedding API keys..."
    cat > "$KEYS_FILE" <<SWIFTEOF
/// API keys embedded at build time for invite code flow.
/// AUTO-GENERATED by build.sh — do NOT commit this version.
enum EmbeddedKeys {
    static let anthropic = "$EMBED_ANTHROPIC"
    static let openai = "$EMBED_OPENAI"
    static let gemini = "$EMBED_GEMINI"
}
SWIFTEOF
    echo "       Keys embedded: anthropic=$( [ -n "$EMBED_ANTHROPIC" ] && echo "yes" || echo "no") openai=$( [ -n "$EMBED_OPENAI" ] && echo "yes" || echo "no") gemini=$( [ -n "$EMBED_GEMINI" ] && echo "yes" || echo "no")"
    KEYS_INJECTED=true
else
    echo "[0/6] No API keys in env — invite code will use empty keys (dev mode)"
    KEYS_INJECTED=false
fi

# ── Step 1: Build universal binary (arm64 + x86_64) ──
echo "[1/6] Building universal binary..."
cd "$SCRIPT_DIR"
swift build --arch arm64 --arch x86_64 -c release 2>&1 | tail -3

BINARY="$BUILD_DIR/apple/Products/Release/$APP_NAME"
if [ ! -f "$BINARY" ]; then
    echo "ERROR: Binary not found at $BINARY"
    exit 1
fi
echo "       $(file "$BINARY" | grep -o 'universal binary with 2 architectures')"

# ── Step 2: Assemble .app bundle ──
echo "[2/6] Assembling .app bundle..."
rm -rf "$APP_DIR"
mkdir -p "$APP_DIR/Contents/MacOS"
mkdir -p "$APP_DIR/Contents/Resources"
mkdir -p "$APP_DIR/Contents/Resources/Glimpse"

# Binary
cp "$BINARY" "$APP_DIR/Contents/MacOS/$APP_NAME"

# Info.plist
cp "$SCRIPT_DIR/Info.plist" "$APP_DIR/Contents/Info.plist"

# Icon
if [ -f "$SCRIPT_DIR/icons/icon.icns" ]; then
    cp "$SCRIPT_DIR/icons/icon.icns" "$APP_DIR/Contents/Resources/icon.icns"
    echo "       Icon: icon.icns"
fi

# Bundled fonts
if [ -f "$SCRIPT_DIR/fonts/Outfit-Variable.ttf" ]; then
    cp "$SCRIPT_DIR/fonts/Outfit-Variable.ttf" "$APP_DIR/Contents/Resources/Outfit-Variable.ttf"
    echo "       Font: Outfit-Variable.ttf"
fi

# Tray icon
if [ -f "$SCRIPT_DIR/icons/tray-icon.png" ]; then
    cp "$SCRIPT_DIR/icons/tray-icon.png" "$APP_DIR/Contents/Resources/tray-icon.png"
    echo "       Tray icon: tray-icon.png"
fi

# swift-shim.js
cp "$SCRIPT_DIR/Glimpse/swift-shim.js" "$APP_DIR/Contents/Resources/Glimpse/swift-shim.js"
echo "       Shim: swift-shim.js"

# Frontend dist — always sync from glimpse-tauri (source of truth)
TAURI_DIST="$SCRIPT_DIR/../glimpse-tauri/dist"
if [ -d "$TAURI_DIST" ]; then
    rm -rf "$SCRIPT_DIR/dist"
    cp -r "$TAURI_DIST" "$SCRIPT_DIR/dist"
    cp -r "$SCRIPT_DIR/dist" "$APP_DIR/Contents/Resources/dist"
    echo "       Frontend: dist/ ($(find "$SCRIPT_DIR/dist" -type f | wc -l | tr -d ' ') files, synced from glimpse-tauri)"
elif [ -d "$SCRIPT_DIR/dist" ]; then
    cp -r "$SCRIPT_DIR/dist" "$APP_DIR/Contents/Resources/dist"
    echo "       Frontend: dist/ ($(find "$SCRIPT_DIR/dist" -type f | wc -l | tr -d ' ') files, LOCAL — may be stale!)"
else
    echo "ERROR: No dist/ found. Run: cd ../glimpse-tauri && npm run build"
    exit 1
    exit 1
fi

# ── Step 3: Code sign ──
echo "[3/6] Code signing..."
if [ "$SIGN_ID" = "-" ]; then
    echo "       Using ad-hoc signing (set CODESIGN_IDENTITY for distribution)"
    codesign --force --deep --sign - \
        --entitlements "$SCRIPT_DIR/Glimpse.entitlements" \
        "$APP_DIR"
else
    echo "       Signing with: $SIGN_ID"
    codesign --force --deep --sign "$SIGN_ID" \
        --entitlements "$SCRIPT_DIR/Glimpse.entitlements" \
        --options runtime \
        "$APP_DIR"
fi
echo "       $(codesign -d --verbose=2 "$APP_DIR" 2>&1 | grep 'Authority\|Signature' | head -1)"

# ── Step 4: Verify ──
echo "[4/6] Verifying bundle..."
# Check binary architectures
ARCHS=$(lipo -archs "$APP_DIR/Contents/MacOS/$APP_NAME" 2>/dev/null || echo "unknown")
echo "       Architectures: $ARCHS"

# Check essential files
for f in Contents/Info.plist Contents/MacOS/Glimpse Contents/Resources/icon.icns \
         Contents/Resources/dist/index.html Contents/Resources/Glimpse/swift-shim.js; do
    if [ -f "$APP_DIR/$f" ]; then
        echo "       ✓ $f"
    else
        echo "       ✗ MISSING: $f"
    fi
done

# App size
APP_SIZE=$(du -sh "$APP_DIR" | cut -f1)
echo "       App size: $APP_SIZE"

# ── Step 5: Create DMG ──
echo "[5/6] Creating DMG..."
DMG_TEMP="$BUILD_DIR/dmg-staging"
DMG_PATH="$BUILD_DIR/$DMG_NAME.dmg"
rm -rf "$DMG_TEMP" "$DMG_PATH"
mkdir -p "$DMG_TEMP"
cp -r "$APP_DIR" "$DMG_TEMP/"

# Create Applications symlink for drag-to-install
ln -s /Applications "$DMG_TEMP/Applications"

# Create DMG
hdiutil create -volname "$APP_NAME" \
    -srcfolder "$DMG_TEMP" \
    -ov -format UDZO \
    "$DMG_PATH" 2>/dev/null

rm -rf "$DMG_TEMP"

DMG_SIZE=$(du -sh "$DMG_PATH" | cut -f1)
echo "       DMG: $DMG_PATH ($DMG_SIZE)"

# ── Step 6: Notarize (if signing identity is not ad-hoc) ──
if [ "$SIGN_ID" != "-" ]; then
    echo "[6/6] Notarization..."
    if command -v xcrun &>/dev/null; then
        TEAM_ID="${APPLE_TEAM_ID:-}"
        APPLE_ID="${APPLE_ID:-}"
        APPLE_PASSWORD="${APPLE_PASSWORD:-}"
        if [ -n "$TEAM_ID" ] && [ -n "$APPLE_ID" ] && [ -n "$APPLE_PASSWORD" ]; then
            xcrun notarytool submit "$DMG_PATH" \
                --apple-id "$APPLE_ID" \
                --team-id "$TEAM_ID" \
                --password "$APPLE_PASSWORD" \
                --wait
            xcrun stapler staple "$DMG_PATH"
            echo "       Notarized and stapled!"
        else
            echo "       Skipped — set APPLE_TEAM_ID, APPLE_ID, APPLE_PASSWORD for notarization"
        fi
    fi
else
    echo "[6/6] Notarization skipped (ad-hoc signing)"
fi

# ── Cleanup: restore empty keys file so real keys never linger in source ──
if [ "$KEYS_INJECTED" = "true" ]; then
    cat > "$KEYS_FILE" <<'SWIFTEOF'
/// API keys embedded at build time for invite code flow.
/// This file is auto-generated by build.sh — do NOT edit manually or commit real keys.
/// The checked-in version has empty strings; build.sh overwrites with real keys for distribution.
enum EmbeddedKeys {
    static let anthropic = ""
    static let openai = ""
    static let gemini = ""
}
SWIFTEOF
    echo "       EmbeddedKeys.swift restored to empty (safe to commit)"
fi

echo ""
echo "=== Build complete! ==="
echo "  App:  $APP_DIR"
echo "  DMG:  $DMG_PATH"
echo ""
echo "To test:"
echo "  open $APP_DIR"
echo ""
echo "To distribute with signing + embedded keys:"
echo "  GLIMPSE_ANTHROPIC_KEY=\"...\" GLIMPSE_OPENAI_KEY=\"...\" GLIMPSE_GEMINI_KEY=\"...\" \\"
echo "  CODESIGN_IDENTITY=\"Developer ID Application: Your Name (TEAMID)\" ./build.sh"
