/// API keys embedded at build time for invite code flow.
/// This file is auto-generated by build.sh — do NOT edit manually or commit real keys.
/// The checked-in version has empty strings; build.sh overwrites with real keys for distribution.
enum EmbeddedKeys {
    static let anthropic = ""
    static let openai = ""
    static let gemini = ""
}
